env:
  es6: true
  jest/globals: true
  node: true
extends: 'eslint:recommended'
globals:
  __DEV__: true
  __PROD__: true
  fetch: false
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: false
plugins:
  - jest
  - react
  - react-native
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console: 0
  no-unused-vars: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict: 0
