export const NOTIFICATION_CONFIRM_SHOW = 'NOTIFICATION/CONFIRM/SHOW';
export const NOTIFICATION_CONFIRM_HIDE = 'NOTIFICATION/CONFIRM/HIDE';

export const NOTIFICATION_ALERT_SHOW = 'NOTIFICATION/ALERT/SHOW';
export const NOTIFICATION_ALERT_HIDE = 'NOTIFICATION/ALERT/HIDE';
